-- MySQL Script generated by MySQL Workbench
-- 05/01/15 22:37:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`rubro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rubro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rubro` (
  `id_rubro` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `status` ENUM('activo','inactivo') NOT NULL,
  PRIMARY KEY (`id_rubro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`empresa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`empresa` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `razon_social` VARCHAR(100) NOT NULL,
  `ruc` VARCHAR(11) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `id_rubro` INT NOT NULL,
  `status` ENUM('activo','inactivo') NOT NULL,
  `foto` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_empresa`),
  INDEX `fk_empresa_rubro1_idx` (`id_rubro` ASC),
  CONSTRAINT `fk_empresa_rubro1`
    FOREIGN KEY (`id_rubro`)
    REFERENCES `mydb`.`rubro` (`id_rubro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`turno` ;

CREATE TABLE IF NOT EXISTS `mydb`.`turno` (
  `id_turno` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `inicio` TIME NOT NULL,
  `fin` TIME NOT NULL,
  PRIMARY KEY (`id_turno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`local`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`local` ;

CREATE TABLE IF NOT EXISTS `mydb`.`local` (
  `id_local` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `latitud` DECIMAL(12,8) NOT NULL,
  `longitud` DECIMAL(12,8) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `zona_reparto_km` INT NOT NULL,
  `id_empresa` INT NOT NULL,
  `id_turno` INT NOT NULL,
  `status` ENUM('activo','inactivo') NOT NULL,
  `costo_envio` DOUBLE(3,1) NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_local`),
  INDEX `fk_local_empresa_idx` (`id_empresa` ASC),
  INDEX `fk_local_turno1_idx` (`id_turno` ASC),
  CONSTRAINT `fk_local_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `mydb`.`empresa` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_local_turno1`
    FOREIGN KEY (`id_turno`)
    REFERENCES `mydb`.`turno` (`id_turno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categoria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `status` ENUM('activo','inactivo') NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `foto` VARCHAR(150) NOT NULL,
  `descipcion` VARCHAR(250) NOT NULL,
  `id_categoria` INT NOT NULL,
  `status` ENUM('activo','inactivo') NOT NULL,
  `id_empresa` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_producto_categoria1_idx` (`id_categoria` ASC),
  INDEX `fk_producto_empresa1_idx` (`id_empresa` ASC),
  CONSTRAINT `fk_producto_categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `mydb`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_empresa1`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `mydb`.`empresa` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`transporte` ;

CREATE TABLE IF NOT EXISTS `mydb`.`transporte` (
  `id_transporte` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido_p` VARCHAR(45) NOT NULL,
  `apellido_m` VARCHAR(10) NOT NULL,
  `domicilio` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `licencia_conducir` VARCHAR(15) NOT NULL,
  `placa_vehiculo` VARCHAR(7) NOT NULL,
  `id_turno` INT NOT NULL,
  `id_local` INT NOT NULL,
  `status` ENUM('activo','inactivo') NOT NULL,
  `longitud` DECIMAL(12,8) NULL,
  `latitud` DECIMAL(12,8) NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_transporte`),
  INDEX `fk_transporte_turno1_idx` (`id_turno` ASC),
  INDEX `fk_transporte_local1_idx` (`id_local` ASC),
  CONSTRAINT `fk_transporte_turno1`
    FOREIGN KEY (`id_turno`)
    REFERENCES `mydb`.`turno` (`id_turno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transporte_local1`
    FOREIGN KEY (`id_local`)
    REFERENCES `mydb`.`local` (`id_local`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido_p` VARCHAR(45) NOT NULL,
  `apellido_m` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `dni` VARCHAR(8) NOT NULL,
  `status` ENUM('activo','inactivo') NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`delivery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`delivery` ;

CREATE TABLE IF NOT EXISTS `mydb`.`delivery` (
  `id_delivery` INT NOT NULL AUTO_INCREMENT,
  `destino_latitud` DECIMAL(12,8) NOT NULL,
  `destino_longitud` DECIMAL(12,8) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `status` ENUM('activo','inactivo') NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_local` INT NOT NULL,
  `paso` ENUM('cancelado','enviado','en camino','en proceso','no enviado') NOT NULL,
  `justificacion_cancelado` TEXT NULL,
  `costo_envio` DOUBLE(3,1) NULL,
  `id_transporte` INT NULL,
  `tipo_comprobante` ENUM('boleta','factura') NULL,
  `nombre_receptor` VARCHAR(150) NULL,
  `dni_receptor` VARCHAR(8) NULL,
  `ruc_receptor` VARCHAR(11) NULL,
  `razon_social_receptor` VARCHAR(50) NULL,
  `direccion_empresa_receptor` VARCHAR(100) NULL,
  `fecha_pedido` DATETIME NOT NULL,
  `fecha_entregado` DATETIME NULL,
  PRIMARY KEY (`id_delivery`),
  INDEX `fk_delivery_transporte1_idx` (`id_transporte` ASC),
  INDEX `fk_delivery_usuario1_idx` (`id_usuario` ASC),
  INDEX `fk_delivery_local1_idx` (`id_local` ASC),
  CONSTRAINT `fk_delivery_transporte1`
    FOREIGN KEY (`id_transporte`)
    REFERENCES `mydb`.`transporte` (`id_transporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_delivery_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_delivery_local1`
    FOREIGN KEY (`id_local`)
    REFERENCES `mydb`.`local` (`id_local`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto_local`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`producto_local` ;

CREATE TABLE IF NOT EXISTS `mydb`.`producto_local` (
  `id_producto` INT NOT NULL,
  `id_local` INT NOT NULL,
  `stock` INT NOT NULL,
  `precio` DOUBLE(7,2) NOT NULL,
  `status` ENUM('activo','inactivo') NOT NULL,
  PRIMARY KEY (`id_producto`, `id_local`),
  INDEX `fk_producto_has_local_local1_idx` (`id_local` ASC),
  INDEX `fk_producto_has_local_producto1_idx` (`id_producto` ASC),
  CONSTRAINT `fk_producto_has_local_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_has_local_local1`
    FOREIGN KEY (`id_local`)
    REFERENCES `mydb`.`local` (`id_local`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `id_producto` INT NOT NULL,
  `id_local` INT NOT NULL,
  `id_delivery` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` DOUBLE(7,2) NOT NULL,
  PRIMARY KEY (`id_producto`, `id_local`, `id_delivery`),
  INDEX `fk_producto_local_has_delivery_delivery1_idx` (`id_delivery` ASC),
  INDEX `fk_producto_local_has_delivery_producto_local1_idx` (`id_producto` ASC, `id_local` ASC),
  CONSTRAINT `fk_producto_local_has_delivery_producto_local1`
    FOREIGN KEY (`id_producto` , `id_local`)
    REFERENCES `mydb`.`producto_local` (`id_producto` , `id_local`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_local_has_delivery_delivery1`
    FOREIGN KEY (`id_delivery`)
    REFERENCES `mydb`.`delivery` (`id_delivery`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sunat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sunat` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sunat` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `ruc` VARCHAR(11) NOT NULL,
  `razon_social` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_empresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reniec`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`reniec` ;

CREATE TABLE IF NOT EXISTS `mydb`.`reniec` (
  `dni` VARCHAR(8) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellido_paterno` VARCHAR(45) NOT NULL,
  `apellido_materno` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `genero` ENUM('M','F') NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
